### ISSUE TITLE
RESW support

### ISSUE THREAD

**Issue by veler** [PabloSR06/DevToys.ResxTranslator#2]
Hello,

I like this RESX translator extension! It's very handy! Have you considered supporting RESW by any chance?

Thanks

**Comment by PabloSR06** [comment]
Hello,

I don't know much about that type of file, but I will look into it.

I see that you know "a little bit" about DevToys. Do you have any advice on how to work with the CLI? I've created [this repo](https://github.com/PabloSR06/DevToys.ExtensionTemplate) as a template. From the information I found, it seems that custom extensions are not yet available in the console.

Anyway, thank you for your comment. I appreciate it.

**Comment by veler** [comment]
> I don't know much about that type of file, but I will look into it.

It is very similar to RESX (it's also a XML), but it's used by UWP, WinUI 3, .NET MAUI and Uno Platform apps.
https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest
Here is a sample: https://github.com/veler/PaZword/blob/main/Windows/Impl/PaZword.Localization/Strings/en/Core.resw

> I see that you know "a little bit" about DevToys.

Haha, I'm the author of DevToys. I hope I'm knowledgeable about it :-)

> Do you have any advice on how to work with the CLI? I've created [this repo](https://github.com/PabloSR06/DevToys.ExtensionTemplate) as a template. From the information I found, it seems that custom extensions are not yet available in the console.

CLI extension are available. There's no extension manager though currently. You have to install the extension manually.
My best recommendation would be to take example on an existing tool, such as Certificate Decoder: https://github.com/DevToys-app/DevToys.Tools/blob/main/src/DevToys.Tools/Tools/EncodersDecoders/Certificate/CertificateDecoderCommandLineTool.cs
Along with the documentation: https://devtoys.app/doc/articles/extension-development/guidelines/command-line-tool.html

Let me know if you have any question :)
